[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd REALVELORA && npm install"]

[phases.build]
cmds = ["cd REALVELORA && npm run build"]

[start]
cmd = "cd REALVELORA && node server/index.js"
